---
hugo_env: &hugo_env
  BASE_URL: https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/

kind: pipeline
name: hugo-s3-deploy

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  - name: deploy-to-s3
    image: plugins/s3
    settings:
      bucket: drone-demo-insset              
      region: us-east-1                       
      source: public/**                          
      target: /                               
      acl: public-read                        
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    when:
      event: push
      branch: master
